### PR TITLE
Add server tests

### PR DESCRIPTION
**Pull request by humphd**
What a great initiative!  I was looking for a way to support your work, and noticed that you don't have any automating testing, so I thought I'd start there.

This PR does a number of things:

1. Adds [Jest](https://jestjs.io/) based tests for the server and database backend.  This includes adding some setup and npm scripts to run the tests (`npm test`) and also gather test coverage info (`npm run coverage`).  The coverage currently sits at ~88%

```
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------|---------|----------|---------|---------|-------------------
All files          |   88.63 |    66.66 |    87.5 |   88.63 |
 server            |   83.33 |      100 |       0 |   83.33 |
  app.js           |   83.33 |      100 |       0 |   83.33 | 13-15
 server/db         |   93.33 |    66.66 |     100 |   93.33 |
  conn.js          |    87.5 |    66.66 |     100 |    87.5 | 5,19
  donations.js     |     100 |      100 |     100 |     100 |
  mask-requests.js |     100 |      100 |     100 |     100 |
 server/routes     |   86.95 |      100 |   85.71 |   86.95 |
  dbapi.js         |    82.6 |      100 |     100 |    82.6 | 13,22,40,66
  index.js         |   85.71 |      100 |       0 |   85.71 | 10
  stripeapi.js     |   93.75 |      100 |     100 |   93.75 | 48
-------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 skipped, 5 passed, 5 of 6 total
Tests:       1 skipped, 15 passed, 16 total
Snapshots:   0 total
Time:        1.021 s
```

2. Adds a continuous integration workflow to run the tests using GitHub Actions on every pull request and merge to `main`
3. Adds tests for the REST API and MongoDB code.  I'm adding an in-memory mock MongoDB server for testing (see [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server)) to simulate working with Atlas.
4. Adds tests for the Stripe integration.  I'm using a mock implementation of the Stripe module (see `__mocks__/stripe.js`), which does the minimum necessary to test your handling of the Stripe API.
5. Breaks up the `server/app.js` file into smaller pieces so I can more easily write tests against the web API.  I've tried not to change it too much of the code itself in this PR, but I did remove a bit of unneeded code, and re-ordered a few things.  Once tests are in place, I can focus on that.
6. Adds some basic error handling to all routes.  This can be improved with better logging, etc. in later PRs.
7. Refactored the donations and mask request DB logic into separate modules that can be re-used vs. having to rely on `axios()` network calls to interact with the db in the Stripe success callback.  It also simplifies the routes.

There is one skipped test in `test/server/routes/index.test.js` that needs to get enabled in a follow-up, but to do that I need to fix some of the ways that paths/URIs are done for the front-end to remove hard-coded paths.  This will also allow me to write front-end tests later on.

It might make sense to tackle auto-deployment in a follow-up, so that it's easier to write the rest of the tests using relative paths and URIs.  I'll have to get some guidance and details on where you deploy, and how, so I can write a workflow for that.

Hopefully you're OK with this direction.  Let me know if you want me to do anything differently.

Looking forward to helping to maintain and improve your code so that it continues to do more good during the pandemic!

### CODE REVIEW

**Comment by mekkim** [comment]
David: You're awesome! A HUGE thank you for this impressive refactoring work!

My only concern aligns with your question about deployment.  We deploy on Dreamhost using Passenger.  The app.js / server.js has to be in a specific format for Passenger to handle the persistence, without triggering the server's "naughty-process-kill-switch".  Details: https://help.dreamhost.com/hc/en-us/articles/215769578-Passenger-overview & https://help.dreamhost.com/hc/en-us/articles/216385637-How-do-I-enable-Passenger-on-my-domain- & https://help.dreamhost.com/hc/en-us/articles/216635268-Passenger-troubleshooting

As long as it conforms to the format Passenger expects, we should be fine.  As to the rest, I'm out of my depth and don't know enough about the tradeoffs to comment, so I'm happy to defer to your expertise.

I'm also quite happy to give you repo access to do updates as you see fit.  I trust you!

**Comment by humphd** [comment]
@mekkim thanks!

I've accepted your invite, and approved this workflow run, which will let me debug it here (it's impossible to test locally), so it will likely fail a few times while I tweak it.

I'll look at Dreamhost and Passenger, and make sure this works with it.  Let me do some more reading and work on this.

**Comment by humphd** [comment]
Based on https://help.dreamhost.com/hc/en-us/articles/216635318-Enabling-Passenger-for-Node-js, I've undone a few things:

1. Renamed `server/app.js` to `server/api.js` and `server/server.js` to `server/app.js`.  This means the `server/app.js` remains the entry-point (same as before).
2. I've disabled caching in the CI installation scripts, which isn't ideal, but fixing it will require removing `server/node_modules`, and I want to understand why it's there in the first place before I pull it out.  Typically you don't want these dependencies in the repo, you want a lock file instead (e.g., binary components in `node_modules` won't work across node/OS versions, so there's not much point in caching them).

I don't think I'll touch more in this PR, until I'm clear if the changes I've made are OK for your deployment workflow--I *think* you should be fine now.  What's your update process for production?  Does it happen automatically, or do you have to do things manually?

I'm a bit unclear which version of node is being used in production. The Passenger docs have a note saying, "The version of Passenger running on DreamHost servers does not currently function with Node.js versions 14+."  I've run the tests on node 12, 14, and 16 and all pass.  In a follow-up, it would be good to get the CI environment matched to what production is using.

Since the tests are now passing, take a look and see if you're OK with this.

**Comment by mekkim** [comment]
You're super fast! Impressive!
1) Excellent.  That should work fine.
2) If I recall correctly, the server node_modules result from the `npm install server` command, but someone more up to date than me should verify this (@devarsh19 @HaiderZaidiDev ?)

I also played around with the Node.js version.  We were using 13 for a while, but then moved to 16 and it seemed to run fine so we've left it at 16.

The update process is manual: One of us pulls main, runs `npm run build` and then manually uploads the contents of the "build" folder to domain_root/public on the webserver via sftp.

**Comment by mekkim** [comment]
Oh, one more thing in the process: If there are changes to any of the server code, a Passenger server reboot is then needed, which is done by touching /tmp/restart.txt and attempting to access the webpage (it is rebooted on first request by comparing timestamp of last touch of restart.txt if newer).

**Comment by mekkim** [comment]
I'll run a local build and see what happens!

**Comment by mekkim** [comment]
Runs fine locally and talks to server fine!  Gonna move live and see.

**Comment by mekkim** [comment]
It's now live at https://donatemask.ca - It all looks like it's working fine to me!  The server restarted ok, so that means Passenger is happy with the file locations.  
I won't recreate /prod/ branch from main for now until we test it a bit, but it's probably all good!

**Pull request merged**
