### PR TITLE
Split address field into three fields

### PR DESCRIPTION
**Pull request by JessEBuchanan**
Two new properties in const RequestForm: city and postalCode. Created new Input components for them that set their values. Address, city and postalCode concatenated to make the address property in const newMaskRequest so that the input to the database remains the same. 

Checked that it renders correctly, not sure how to check it doesn't affect the backend submission to the database, but the newMaskRequest format remains the same so not expecting issues with the database.

Attached screenshot of render of the request mask page. 

splitAddress

### CODE REVIEW

**Comment by JessEBuchanan** [comment]
I just saw the issue for this which calls for separate fields for province and apt #. I can add those soon, sorry I missed the issue page before I had started the work.

**Comment by JessEBuchanan** [comment]
Latest commit separates the city and province into separate input fields. Added input field for apartment. Needs a test with submission to the database --> I added something to distinguish between there being an apartment # or not but not entirely sure it will submit correctly.

**Comment by Sync271** [comment]
Sometime in the future, we could implement something like:
```diff
- const [name, setName] = useState("");
- const [email, setEmail] = useState("");
- const [address, setAddress] = useState("");

+ const [maskData, setMaskData] = useState({
+   name: "",
+   email: "",
+   address: "",
+    });
```
and then set each state like `setMaskData({...maskData, name: Jess})`
Basically have one object and then update it's state

**Review by Sync271 — APPROVED** [review]
LGTM! 🙌

**Comment by devarsh19** [comment]
> Sometime in the future, we could implement something like:
> 
> ```diff
> - const [name, setName] = useState("");
> - const [email, setEmail] = useState("");
> - const [address, setAddress] = useState("");
> 
> + const [maskData, setMaskData] = useState({
> +   name: "",
> +   email: "",
> +   address: "",
> +    });
> ```
> 
> and then set each state like `setMaskData({...maskData, name: Jess})` Basically have one object and then update it's state

Absolutely agree, that would become more easy to manage all the state values

**Pull request merged**
