### PR TITLE
When Clicked, "Request" now takes you to /request

### LINKED ISSUE #35: Request Button in Second Box of Summary Page Not Working
On the summary page, clicking the request button on the "Total Mask Requests" box has no effect.  Should redirect to https://requestmask.ca.

### PR DESCRIPTION
**Pull request by Sync271**
Fixes #35 

I noticed even Donate isn't working, but there are 2 donate buttons but only one is displayed.
If you can clear that out, I'll fix donate button too

### CODE REVIEW

**Comment by mekkim** [comment]
Sweet, thanks!  We haven't yet figured out why all the donate buttons aren't displaying.  There should be the main page's form, Paypal, Patreon, Buy Me a Coffee, and Go Fund Me.  They seem to randomly not show up.

**Comment by Sync271** [comment]
I'd like to contribute more and j noticed you're main branch is pretty much empty, any particular reason? I'm just curious.

**Comment by mekkim** [comment]
That's kind of you, thanks!  We've been using the /dev/ branch as primary dev and /prod/ branch as what's currently live pushed onto the web server.  Your best bet is to clone /dev/ and then submit pull requests into it.

**Comment by Sync271** [comment]
I see, what ends up happening is only main branch commits are considered towards contributions and because of that you might be losing out on a lot more people who are willing to help

**Comment by mekkim** [comment]
Interesting!  Did not know that.  @HaiderZaidiDev: Can we move /prod/ to /main/ and the old /main/ to /old/ (or something) and then we can push /dev/ to /main/ and people can get proper contribution tracking?

**Pull request merged**
